# File:   Makefile.test
# Author: Michael Alpenfels
# Date:   17 October 2021
# Descr:  Test Makefile for ENCE260 assignment 2 (2021).

# Definitions.
CC = gcc
CFLAGS = -Wall -Wstrict-prototypes -Wextra -g -I. -I../../utils -I../../drivers -I../../drivers/test

DEL = rm


# Default target.
all: run_tests.out

# Compile: create object files from C source files.

maze_tests.o: test/maze_tests.c test/maze_tests.h test/ucfk_assertions.h test/position_tests.h bitmap.h position.h maze.h
	$(CC) -c $(CFLAGS) $< -o $@

position_tests.o: test/position_tests.c test/position_tests.h position.h
	$(CC) -c $(CFLAGS) $< -o $@

bitmap_tests.o: test/bitmap_tests.c test/bitmap_tests.h test/ucfk_assertions.h bitmap.h position.h
	$(CC) -c $(CFLAGS) $< -o $@

ucfk_assertions.o: test/ucfk_assertions.c test/ucfk_assertions.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

run_tests.o: test/run_tests.c test/ucfk_assertions.h ../../drivers/test/system.h ../../drivers/button.h game_controller.h position.h maze.h levels.h
	$(CC) -c $(CFLAGS) $< -o $@

game_controller-test.o: game_controller.c game_controller.h maze.h input.h levels.h position.h move.h menus.h
	$(CC) -c $(CFLAGS) $< -o $@

pio-test.o: ../../drivers/test/pio.c ../../drivers/test/pio.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

timer-test.o: ../../drivers/test/timer.c ../../drivers/test/timer.h
	$(CC) -c $(CFLAGS) $< -o $@

pacer-test.o: ../../utils/pacer.c ../../drivers/test/system.h ../../drivers/test/timer.h ../../utils/pacer.h
	$(CC) -c $(CFLAGS) $< -o $@

led-test.o: ../../drivers/led.c ../../drivers/led.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

mgetkey-test.o: ../../drivers/test/mgetkey.c ../../drivers/test/mgetkey.h
	$(CC) -c $(CFLAGS) $< -o $@

system-test.o: ../../drivers/test/system.c ../../drivers/test/system.h ../../drivers/test/avrtest.h ../../drivers/test/mgetkey.h ../../drivers/test/pio.h
	$(CC) -c $(CFLAGS) $< -o $@

position-test.o: position.c ../../drivers/test/pio.c ../../drivers/test/pio.h position.h
	$(CC) -c $(CFLAGS) $< -o $@

navswitch-test.o: ../../drivers/navswitch.c ../../drivers/navswitch.h
	$(CC) -c $(CFLAGS) $< -o $@

levels-test.o: levels.c levels.h maze.h bitmap.h position.h
	$(CC) -c $(CFLAGS) $< -o $@

button-test.o: ../../drivers/button.c ../../drivers/button.h
	$(CC) -c $(CFLAGS) $< -o $@

bitmap-test.o: bitmap.c ../../drivers/test/pio.c ../../drivers/test/pio.h bitmap.h position.h
	$(CC) -c $(CFLAGS) $< -o $@

maze-test.o: maze.c bitmap.h maze.h position.h
	$(CC) -c $(CFLAGS) $< -o $@

move-test.o: move.c move.h maze.h position.h input.h
	$(CC) -c $(CFLAGS) $< -o $@

input-test.o: input.c input.h ../../drivers/navswitch.h ../../drivers/button.h position.h
	$(CC) -c $(CFLAGS) $< -o $@

display-test.o: ../../drivers/display.c ../../drivers/display.h ../../drivers/test/system.h ../../drivers/ledmat.h
	$(CC) -c $(CFLAGS) $< -o $@

ledmat-test.o: ../../drivers/ledmat.c ../../drivers/test/pio.h ../../drivers/test/system.h ../../drivers/ledmat.h
	$(CC) -c $(CFLAGS) $< -o $@

font-test.o: ../../utils/font.c ../../drivers/test/system.h ../../utils/font.h
	$(CC) -c $(CFLAGS) $< -o $@

tinygl-test.o: ../../utils/tinygl.c ../../utils/tinygl.h ../../drivers/test/system.h ../../drivers/display.h ../../utils/font.h
	$(CC) -c $(CFLAGS) $< -o $@

menus-test.o: menus.c menus.h ../../drivers/led.h ../../drivers/button.h ../../utils/tinygl.h ../../fonts/font5x7_1.h ../../utils/font.h
	$(CC) -c $(CFLAGS) $< -o $@

game_controller-test.o: game_controller.c game_controller.h maze.h position.h input.h levels.h move.h menus.h
	$(CC) -c $(CFLAGS) $< -o $@

# Link: create ELF output file from object files.
run_tests.out: run_tests.o ucfk_assertions.o maze_tests.o pio-test.o system-test.o bitmap-test.o timer-test.o pacer-test.o maze-test.o position-test.o move-test.o input-test.o navswitch-test.o game_controller-test.o button-test.o levels-test.o led-test.o menus-test.o display-test.o tinygl-test.o ledmat-test.o font-test.o mgetkey-test.o bitmap_tests.o position_tests.o
	$(CC) $(CFLAGS) $^ -o $@ -lrt -lm


# Target: clean project.
.PHONY: clean
clean: 
	-$(DEL) *.o *.out *.hex

